---
- name: Configure unattended-upgrades
  become: yes
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Install unattended-upgrades
  become: yes
  apt:
    name: unattended-upgrades
    state: present
