- name: Ensure desktop configuration using dconf
  ansible.builtin.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ config.dconf }}"

- name: Copy wallpaper file
  copy:
    src: files/wallpaper.jpg
    dest: "{{ ansible_env.HOME }}/.wallpaper.jpg"
    mode: "0644"

- name: Set wallpaper
  community.general.dconf:
    key: "/org/cinnamon/desktop/background/picture-uri"
    value: "'file://{{ ansible_env.HOME }}/.wallpaper.jpg'"
