- name: Ensure desktop configuration using dconf
  become: yes
  become_user: "{{ default_user }}"
  ansible.builtin.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ config.dconf }}"

- name: Copy wallpaper file
  become: yes
  become_user: "{{ default_user }}"
  copy:
    src: files/wallpaper.jpg
    dest: "/home/{{ default_user }}/.wallpaper.jpg"
    mode: "0644"

- name: Set wallpaper
  become: yes
  become_user: "{{ default_user }}"
  community.general.dconf:
    key: "/org/cinnamon/desktop/background/picture-uri"
    value: "'file:///home/{{ default_user }}/.wallpaper.jpg'"
